version: '3'
services:
 web:
  image: "nginx:stable-alpine-perl"
  ports:
   - "8080:80"
  volumes:
   - ./socks:/tmp/run/
   - ./public:/var/www/html:ro
   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
 redis:
  image: "redis:alpine"
  volumes:
    - ./socks:/tmp/run/
    - ./redis.conf:/redis.conf:ro
  command: [ "redis-server", "/redis.conf" ]
 php7:
  image: "php:7-fpm-alpine"
  volumes:
   - ./socks:/tmp/run/
   - ./php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
   - ./public:/var/www/html